name: Build Miro GKI Vendor
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build Script
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison lld llvm-dev libssl-dev ccache libelf-dev
          
      - name: Download Toolchain (AOSP Clang)
        run: |
          mkdir clang
          # Pakai link prebuilt yang lebih stabil dan lengkap
          curl -LSs https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522830.tar.gz -o clang.tar.gz
          tar -xf clang.tar.gz -C clang
          echo "$(pwd)/clang/bin" >> $GITHUB_PATH

      - name: Clone Kernel Source
        uses: actions/checkout@v4
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: bsp-miro-v-oss
          path: kernel-source
          fetch-depth: 1

      - name: Setup Official KernelSU
        run: |
          cd kernel-source
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Build Kernel
        run: |
          cd kernel-source
          
          # AUTO-DETECT DEFCONFIG: Mencari file yang mengandung kata 'miro' atau 'sun' di folder configs
          DEFCONFIG=$(find arch/arm64/configs/vendor -name "*miro*" -o -name "*sun*" | head -n 1 | xargs basename)
          echo "Menggunakan Defconfig: $DEFCONFIG"
          
          # Proses Compile
          make O=out ARCH=arm64 vendor/$DEFCONFIG
          make -j$(nproc --all) O=out ARCH=arm64 \
            CC=clang \
            HOSTCC=clang \
            HOSTCXX=clang++ \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            LD=ld.lld \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            LLVM=1 \
            LLVM_IAS=1

      - name: Package with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3
          rm -rf AnyKernel3/.git
          cp kernel-source/out/arch/arm64/boot/Image AnyKernel3/
          cd AnyKernel3 && zip -r9 "../Kernel-Miro-KSU-Official.zip" .

      - name: Upload Flashable Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Miro-KSU-Official
          path: Kernel-Miro-KSU-Official.zip
